module.exports = {
  DJ: "DJ",
  ADMIN: "Administrator",
  MANAGE_GUILD: "ManageGuild",
  MANAGE_MESSAGES: "ManageMessages",
  MANAGE_CHANNELS: "ManageChannels",
  CONNECT: "Connect",
  SPEAK: "Speak",
  MUTE_MEMBERS: "MuteMembers",
  DEAFEN_MEMBERS: "DeafenMembers",
  MOVE_MEMBERS: "MoveMembers",
  USE_VAD: "UseVAD",
  PRIORITY_SPEAKER: "PrioritySpeaker",
  STREAM: "Stream",
  EMBED_LINKS: "EmbedLinks",
  ATTACH_FILES: "AttachFiles",
  READ_MESSAGE_HISTORY: "ReadMessageHistory",
  USE_EXTERNAL_EMOJIS: "UseExternalEmojis",
  ADD_REACTIONS: "AddReactions",
  SEND_MESSAGES: "SendMessages",
};
